EWMS/EWMS/urls.py
from masterData import views as masterData_views
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from dashboard import views as dbviews

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', masterData_views.landingpage, name="landing"),
    path('register/', masterData_views.registerPage, name="register"),
    path('e404/', masterData_views.errorpage, name="e404"),

    path('login/', masterData_views.loginPage, name="login"),
    path('logout/', masterData_views.logoutUser, name="logout"),

    path("home/", masterData_views.homepage, name="home"),
    path("ota/", masterData_views.ota, name="ota"),

    path("addwarehouse/", masterData_views.WarehouseCreateView.as_view(),
         name="addwarehouse"),
    path("addzone/", masterData_views.ZoneCreateView.as_view(), name="addzone"),
    path("addbin/", masterData_views.BinCreateView.as_view(), name="addbin"),
    path("addsupp/", masterData_views.SupplierCreateView.as_view(), name="addsupp"),
    path("addcustomer/", masterData_views.CustomerCreateView.as_view(),
         name="addcustomer"),

    path("ird/", masterData_views.ItemRecieveDetailsCreateView.as_view(), name="ird"),
    path("inventory/", masterData_views.InventoryCreateView.as_view(), name="inventory"),
    path("itemmaster/", masterData_views.ItemMasterCreateView.as_view(),
         name="itemmaster"),

    path("zone_list/<int:id>", masterData_views.zone_list, name="zone_list"),
    path("bin_list/<int:id>", masterData_views.bin_list, name="bin_list"),

    path("orm/", masterData_views.OrderRecieveMasterCreateView.as_view(), name="orm"),
    path("ord/<int:id>", masterData_views.orderreceivedetailview, name="ord"),
    path("allorderdetail/<int:id>",
         masterData_views.allOrderDetails, name="allorderdetail"),

    path("orderprocess/<int:id>",
         masterData_views.orderprocesscreateview, name="orderprocess"),
    path("orderapproval/<int:id>",
         masterData_views.orderApprovalView, name="orderapproval"),

    path("delete_order_event/<int:id>",
         masterData_views.deleteorder, name="deleteOrder"),
    path("delete_order_detail/<int:id>",
         masterData_views.deletedetail, name="deleteDetail"),

    path("pickslip/<int:id>", masterData_views.pickslip,
         name="pickslip"),  
    path("suphome/", masterData_views.suphome, name="suphome"),

    path("superapproval/", masterData_views.superapproval, name="superapproval"),
    path("updatedetail/<int:id>", masterData_views.updatedetail, name="updatedetail"),

    path("inventoryDisplay/<int:id>",
         masterData_views.inventoryDisplay, name="inventory_display"),

    path("warehouselist/", masterData_views.warehouselist, name="warehouselist"),
    path("allzonelist/", masterData_views.allzonelist, name="allzonelist"),
    path("allbinlist/", masterData_views.allbinlist, name="allbinlist"),
    path('', include('authentication.urls')),
    path('dashboard/items/', dbviews.items, name="items"),
    path('dashboard/orders/', dbviews.orders, name="orders"),
    path('warelistsup/', masterData_views.warelistsup, name="warelistsup"),
    path('zonelistsup/', masterData_views.zonelistsup, name="zonelistsup"),
    path('binlistsup/', masterData_views.binlistsup, name="binlistsup"),
    path("supzonelist_id/<int:id>",
         masterData_views.zone_list_sup, name="supzonelist_id"),
    path("supbinlist_id/<int:id>",
         masterData_views.bin_list_sup, name="supbinlist_id"),
    path("inventoryDisplaysup/<int:id>",
         masterData_views.inventoryDisplaysup, name="inventory_displaysup"),
     
     path("inventory/<int:id>", masterData_views.inventory, name="inventory"),
     path("ihome/", masterData_views.ihome, name="ihome"),
     path("dispa/", masterData_views.dispatchorder, name="dispa"),
     path("gat/<int:id>", masterData_views.gatepass, name="gat"),
     path("getgp/<int:id>", masterData_views.getgp, name="getgp"),
     path("getsn/<int:id>", masterData_views.getsn, name="getsn"),




     path("doapi/", masterData_views.DispatchOrderAPI.as_view(), name="doapi"),
     path("ordapi/", masterData_views.OrderRecieveDetailAPI.as_view(), name="ordapi"),
     path("dodapi/", masterData_views.DispatchOrderDetailsAPI.as_view(), name="dodapi"),

     path("irdapi/", masterData_views.ItemRecieveDetailsAPI.as_view(), name="irdapi"),
     path("itapi/", masterData_views.ItemTaggingAPI.as_view(), name="itapi"),

     path("dapi/", masterData_views.VerificationAPI.as_view(), name="dapi"),
     
     

     path("api-auth/", include('rest_framework.urls')),
     path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
     path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
     path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

EWMS/masterData/models.py
from pyexpat import model
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save


#(Rishabh Baranwal)
ITEM_CATEGORY_CHOICES = (
    ('Sensor', 'Sensor'),
    ('Engine', 'Engine'),
    ('Camera', 'Camera'),
    ('Cormen', 'Cormen'),
    ('Campbell', 'Campbell'),
    ('Thomas Calculus', 'Thomas Calculus'),
    ('Swevel chair', 'Swevel chair'),
    ('Minika Sofa', 'Minika Sofa'),
    ('Lamp Shed', 'Lamp Shed'),
    ('Olives', 'Olives'),
    ('Jalapeno', 'Jalapeno'),
    ('Paparika', 'Paparika'),
    ('Paracitamol', 'Paracitamol'),
    ('Sorbitol', 'Sorbitol'),
    ('Cetrizine', 'Cetrizine'),
)

ITEM_CATEGORY_CHOICES_ITEMCODE = (
    ('1000', 'Sensor'),
    ('1001', 'Engine'),
    ('1002', 'Camera'),
    ('1003', 'Cormen'),
    ('1004', 'Campbell'),
    ('1005', 'Thomas Calculus'),
    ('1006', 'Swevel chair'),
    ('1007', 'Minika Sofa'),
    ('1008', 'Lamp Shed'),
    ('1009', 'Olives'),
    ('1010', 'Jalapeno'),
    ('1011', 'Paparika'),
    ('1012', 'Paracitamol'),
    ('1013', 'Sorbitol'),
    ('1014', 'Cetrizine'),
)


ITEM_SKU_CHOIES = (
    ('pcs', 'Pcs'),
    ('box', 'Box'),
)
#
#
# did not find its purpose in any of classes
INVENTORY_TYPE_CHOICES = (
    ('fast-moving', 'Fast Moving'),
    ('slow-moving', 'Slow Moving'),
    ('seasonal', 'Seasonal'),
)
#
#
#
ITEM_MOVEMENT_TYPE_CHOICES = (
    ('fifo', 'FIFO'),
    ('lifo', 'LIFO'),
    ('random', 'RANDOM'),
)
ROLENAME_CHOICES = (
    ('worker', 'Worker'),
    ('supervisor', 'Supervisor'),
    ('customer', 'Customer'),
    ('supplier', 'Supplier'),
)
FLAG_TYPE_CHOICES = (
    ('false', 'false'),
    ('true', 'true'),
)

# all many to one or one to many relations are made by using foreign key concepts

# order for order dispatch will be - warehouse - zone - bin - orderecievemaster- orderapproval - orderrecievedetails(to be done by the worker) - orderprocessing - inventory - orderdispatch - dispatchdetails

# order for item recieve will be - warehouse - zone - bin - itemrecievemaster- recieveapproval - itemrecievedetails(to be done by the worker) -inventory- dockallocation - itemtagging - itemaster

# for orderrecievemaster, itemrecievemaster user coming from superuser

# the basic user model that has user roles(Ansh Gupta)
# 

#Ansh Gupta
class Role(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_worker = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=not True)
    is_supervisor = models.BooleanField(default=not True)

    def __str__(self):
        return self.user.username + 'Role'

# Ansh Gupta
def create_user_role(sender, instance, created, *args, **kwargs):
    if created:
        newrole = Role.objects.create(user=instance)
        newrole.save()


post_save.connect(create_user_role, sender=User)


#(Rishabh Baranwal) model of new user
class NewUser(models.Model):
    UserId = models.AutoField(primary_key=True)
    UserName = models.CharField(max_length=50)
    MgrId = models.CharField(max_length=50)
    RoleName = models.CharField(
        max_length=15, choices=ROLENAME_CHOICES, default='worker')

    def __str__(self):
        return str(self.UserId)

# warehouse is a class that stores the information about the location of warehouse (Rishabh Baranwal)
class WareHouse(models.Model):  # done
    WareHouseId = models.AutoField(primary_key=True)
    WareHouseName = models.CharField(max_length=256)
    WareHouseAddress = models.CharField(max_length=256)

    def __str__(self):
        return str(self.WareHouseName)

# zone area is one column in warehouse which (Rishabh Baranwal)
class Zone_Area(models.Model):  # done
    ZoneId = models.AutoField(primary_key=True)
    ZoneName = models.CharField(max_length=256)
    WareHouseId = models.ForeignKey(WareHouse, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.ZoneName)

# bin is one section in zone area (Rishabh Baranwal)
class Bin(models.Model):  # done
    BinId = models.AutoField(primary_key=True)
    BinName = models.CharField(max_length=256)
    ZoneId = models.ForeignKey(Zone_Area, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.BinName)

# supplier supplies item that are ordered by the warehouse (Urvish Mehta Kaushal)
class Supplier(models.Model):  # done
    SupplierId = models.AutoField(primary_key=True)
    SupplierName = models.CharField(max_length=256)
    SupplierAddress = models.CharField(max_length=256)
    SupplierCity = models.CharField(max_length=256)
    ContactNumber = models.CharField(max_length=20)

    def __str__(self):
        return str(self.SupplierId)

# customer orders order that have to be delivered by the warehouse (Ansh Gupta)
class Customer(models.Model):  # done
    CustomerId = models.AutoField(primary_key=True)  # auto generated
    CustomerName = models.CharField(max_length=256)
    CustomerAddress = models.CharField(max_length=256)
    CustomerCity = models.CharField(max_length=256)
    ContactNumber = models.CharField(max_length=15)  # Telephonic reference
    CustomerEmail = models.EmailField(max_length=256)

    def __str__(self):
        return str(self.CustomerName)


# to store the orders by customers (Ansh Gupta)
class OrderRecieveMaster(models.Model):  # 1
    OrderId = models.AutoField(primary_key=True)
    OrderDate = models.DateTimeField(default=timezone.now)
    CustomerId = models.ForeignKey(Customer, on_delete=models.CASCADE)  # randomly selected from DB
    # error giving to change   #one one field
    #UserId = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    isApproved = models.CharField(
        max_length=10, choices=FLAG_TYPE_CHOICES, default='false')

    def __str__(self):
        return str(self.OrderId)


# extension of order master that stores quantity and item code (Ansh Gupta)
class OrderRecieveDetail(models.Model):  # 2
    OrderId = models.ForeignKey(OrderRecieveMaster, on_delete=models.CASCADE)
    ItemCode = models.CharField(
        max_length=20, choices=ITEM_CATEGORY_CHOICES_ITEMCODE, default='1000')
    Qty = models.IntegerField(default=0)
    isApproved = models.CharField(
        max_length=10, choices=FLAG_TYPE_CHOICES, default='false')
    BatchNo = models.CharField(max_length=256, default=1000)

    def __str__(self):
        return str(self.id)

# this class contains complete detail of order which has to be process by the manager (Urvish Mehta Kaushal)
class OrderProcessing(models.Model):  # 3
    OPId = models.AutoField(primary_key=True)
    OPDate = models.DateTimeField(default=timezone.now)
    # one one field not sure # here this one ot one is scorrect
    OrderId = models.OneToOneField(
        OrderRecieveDetail, on_delete=models.CASCADE)
    Remarks = models.CharField(max_length=256, default="Processed")
    ZoneId = models.ForeignKey(Zone_Area, on_delete=models.CASCADE)
    BinId = models.ForeignKey(Bin, on_delete=models.CASCADE)
    # UserId = models.ForeignKey(NewUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.OPId)

# this class is for confirmation of the order processing, if it is apporved, the quantities will be changed in the warehouse (Yash Kadam)
class OrderApproval(models.Model):  # 4
    OdrApprovalId = models.AutoField(primary_key=True)
    OdrApprovalDate = models.DateTimeField(default=timezone.now)
    OrderId = models.OneToOneField(
        OrderRecieveMaster, on_delete=models.CASCADE)
    Remarks = models.CharField(max_length=256)

    def __str__(self):
        return str(self.OdrApprovalId)

# to store orders by warehouse (Yash Kadam)
class ItemRecieveMaster(models.Model):
    RecieveId = models.AutoField(primary_key=True)
    RecieveDate = models.DateTimeField(default=timezone.now)
    # randomly selected form the db
    SupplierId = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    VechileNo = models.CharField(max_length=256)
    # error giving to change    #one one field
    UserId = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    # has to be one one field not sure
    RecApprovalStatus = models.CharField(max_length=256)
    RecTaggingStatus = models.CharField(max_length=256)
    RecDockingStatus = models.CharField(max_length=256)

    def __str__(self):
        return str(self.RecieveId)

# extension of item master that stores quantity and item code (Swapnaneel Basu)
class ItemRecieveDetails(models.Model):  # ---- to be done
    # taken form itemrecievemaster
    RecieveId = models.ForeignKey(ItemRecieveMaster, on_delete=models.CASCADE)
    ItemCode = models.CharField(
        max_length=20, choices=ITEM_CATEGORY_CHOICES_ITEMCODE, default='1000')
    BatchNo = models.CharField(max_length=256)
    RecieveQty = models.IntegerField(default=0)

# approval for recieving goods, status check by manager (Yash Kadam)
class ReceiveApproval(models.Model):
    RecApproalId = models.AutoField(primary_key=True)
    RecApproalDate = models.DateTimeField(default=timezone.now)
    ReceiveId = models.ForeignKey(ItemRecieveMaster, on_delete=models.CASCADE)
    Remarks = models.CharField(max_length=300)
    UserId = models.ForeignKey(NewUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.RecApproalId)

# contains the information about the inventory, will increase decrease accordingly (Urvish Mehta Kaushal)
class Inventory(models.Model):  # ---- to be done
    ItemId = models.AutoField(primary_key=True)
    ItemCode = models.CharField(max_length=20, choices=ITEM_CATEGORY_CHOICES_ITEMCODE, default='1000')
    InvDate = models.DateTimeField(default=timezone.now)
    MovementType = models.CharField(max_length=10, choices=ITEM_MOVEMENT_TYPE_CHOICES, default='fifo')

    # TransactionId = models.ForeignKey()

    Qty = models.IntegerField(default=0)
    BinId = models.ForeignKey(Bin, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.ItemId)

EWMS/masterData/templates/masterData/404page.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <style>
            *{
                transition: all 0.6s;
            }
            
            html {
                height: 100%;
            }
            
            body{
                font-family: 'Lato', sans-serif;
                color: #888;
                margin: 0;
            }
            
            #main{
                display: table;
                width: 100%;
                height: 100vh;
                text-align: center;
            }
            
            .fof{
                  display: table-cell;
                  vertical-align: middle;
            }
            
            .fof h1{
                  font-size: 50px;
                  display: inline-block;
                  padding-right: 12px;
                  animation: type .5s alternate infinite;
            }
            
            @keyframes type{
                  from{box-shadow: inset -3px 0px 0px #888;}
                  to{box-shadow: inset -3px 0px 0px transparent;}
            }
        </style>
        <<link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
        
        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
    </head>
    <body>
        <div id="main">
            <div class="fof">
                    <h1>More qty than in inventory</h1>
                    <br>
                    <a href="{% url 'logout'%}">Return to home </a>
            </div>
    </div>
        
        <script src="" async defer></script>
    </body>
</html>

EWMS/masterData/templates/masterData/dispatchorderdetail_form.html
{% extends 'masterData/base.html' %}
{% block content %}
<form method = "POST">
    {% csrf_token %}
<div>
    {{form.as_p}}
</div>
<button class = "btn btn-outline-success btn-sm" type ="submit">Submit</button>
</form>
{% endblock %}

EWMS/masterData/templates/masterData/gatepass.html
{% extends 'masterData/base.html' %}
{% load static %}

{% block content %}

<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a href="{%url 'home' %}" class="navbar-brand mx-4 mb-3">
            <h5 class="text-primary">Manager Dashboard</h5>
        </a>
       
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="{% static 'img/testimonial-1.jpg' %}" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{{user.username}}</h6>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'home'%}" class="nav-item nav-link "><i class="fa fa-tachometer-alt me-2"></i>Home</a>
            <a href="{% url 'addwarehouse' %}" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Add Warehouse</a>
            <a href="{% url 'supplier'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Add Supplier</a>
            <a href="{% url 'addcustomer'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Add Customer</a>


            {% comment %} <a href="{% url 'inventory'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Inventory</a> {% endcomment %}
            <a href="{% url 'ita'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Item Approval</a>

            <a href="{% url 'ota'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Order Approval</a>
            <a href="{% url 'ihome'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Inventory</a>
            <a href="{% url 'dispa'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Order Dispatch</a>

        </div>
    </nav>
</div>
<!-- Sidebar End -->

    <div class="content">
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
            <div class="navbar-nav align-items-center ms-auto">        
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <span class="d-none d-lg-inline-flex">{{user.username}}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a href=" {% url 'logout'%}" class="dropdown-item">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Navbar End -->
          
        <br>
        
        <div class="row">         {% comment %}brings card to the center of screen{% endcomment %}
            <div class="col-11 mx-auto">     {% comment %}reduce the spread of card {% endcomment %}
                 <div class="card shadow border">        {% comment %}brings out the card {% endcomment %}
                    <div class="card-body d-flex flex-column align-items-center">
            <h3 align="center">Dispatch Order Detail</h3>
            <div class="col-12">
                <div class="bg-light rounded h-100 p-4">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Order Id</th>
                                    <th scope="col">Item</th>
                                    <th scope="col">Batch No</th>
                                    <th scope="col">QR Code</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in d%}
                                <tr>
                                    <td>{{ i.OrderId }}</td>
                                    <td>{{ i.get_ItemCode_display  }}</td>
                                    <td>{{ i.BatchNo }}</td>
                                    <td>{{ i.QRCode|truncatechars:16}} </td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        
                            <a href="{% url 'getgp' doid %}" class="btn btn-sm btn-outline-success">Generate Gate pass</a>                            
                                <a  
                                    href="{% url 'getsn' doid %}"
                                    class="btn btn-sm btn-outline-success"
                                >
                                    Generate Shipping Note
                                </a>
                                
                    </div>
                </div>
            </div>
            <br>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
{% endblock %}

EWMS/masterData/templates/masterData/ihome.html
{% extends 'masterData/base.html' %}
{% load static %}

{% block content %}

<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
    <nav class="navbar bg-light navbar-light">
        <a href="{%url 'home' %}" class="navbar-brand mx-4 mb-3">
            <h5 class="text-primary">Manager Dashboard</h5>
        </a>
       
        <div class="d-flex align-items-center ms-4 mb-4">
            <div class="position-relative">
                <img class="rounded-circle" src="{% static 'img/testimonial-1.jpg' %}" alt="" style="width: 40px; height: 40px;">
                <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
            </div>
            <div class="ms-3">
                <h6 class="mb-0">{{user.username}}</h6>
            </div>
        </div>
        <div class="navbar-nav w-100">
            <a href="{% url 'home'%}" class="nav-item nav-link "><i class="fa fa-tachometer-alt me-2"></i>Home</a>
            <a href="{% url 'addwarehouse' %}" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Add Warehouse</a>
            <a href="{% url 'supplier'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Add Supplier</a>
            <a href="{% url 'addcustomer'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Add Customer</a>


            {% comment %} <a href="{% url 'inventory'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Inventory</a> {% endcomment %}
            <a href="{% url 'ita'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Item Approval</a>

            <a href="{% url 'ota'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Order Approval</a>
            <a href="{% url 'ihome'%}" class="nav-item nav-link active"><i class="fa fa-keyboard me-2"></i>Inventory</a>
            <a href="{% url 'dispa'%}" class="nav-item nav-link"><i class="fa fa-keyboard me-2"></i>Order Dispatch</a>

        </div>
    </nav>
</div>
<!-- Sidebar End -->

    <div class="content">
        <!-- Navbar Start -->
        <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
            <div class="navbar-nav align-items-center ms-auto">        
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        <span class="d-none d-lg-inline-flex">{{user.username}}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                        <a href=" {% url 'logout'%}" class="dropdown-item">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
        <!-- Navbar End -->
          
        <br>
        
        <div class="row">         {% comment %}brings card to the center of screen{% endcomment %}
            <div class="col-11 mx-auto">     {% comment %}reduce the spread of card {% endcomment %}
                 <div class="card shadow border">        {% comment %}brings out the card {% endcomment %}
                    <div class="card-body d-flex flex-column align-items-center">
            <h3 align="center">Inventory List</h3>
            <div class="col-12">
                <div class="bg-light rounded h-100 p-4">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Item Code</th>
                                    <th scope="col">Item Name</th>
                                    <th scope="col">Quantity</th>
                                    <th scope="col">Bin</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in inv %}
                                <tr>
                                    <td>{{ i.ItemCode }}</td>
                                    <td>{{ i.get_ItemCode_display }}</td>
                                    <td>{{ i.Qty }}</td>
                                    <td>{{i.BinId}} </td>
                                    <td>
                                    <a  
                                        href="{% url 'inventory' i.ItemId%}"
                                        class="btn btn-sm btn-outline-success"
                                    >
                                        Inventory Summary
                                    </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <br>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
{% endblock %}